var array = [{question: "2012.CBee.1 A treaty ending one of these conflicts was supplemented by the Treaty of the Bogue. Lin Zexu's agitations against a certain substance caused these wars. Marked by a period of unequal treaties, they were ended by the Treaties of Nanking and Tientsin. For the point, give the name for these conflicts between Britain and China over the namesake drug.", ANSWER: "Opium Wars"},
             {question: "2013.CBee.3 This set of conflicts resulted in the burning of the Old Summer Palace, and one portion of this set of conflicts was caused in part by Charles Elliot's actions in Kowloon. Another portion of this set of conflicts was set off by the storming of the HMS Arrow. Treaties signed at Wangxia and Tientsin were part of the Unequal Treaties during this set of conflicts, which also included the Treaty of Nanking. For the point, identify this conflict between the Qing Dynasty and Great Britain, sparked by imports of a certain drug.", ANSWER: "Opium Wars"},
             {question: "2013.NatsBee.2 This two-word term describes a group of documents that includes the one that created the extended Railway Zone, the Twenty One Demands. One document described by this two-word term prompted the Triple Intervention; that one also resulted in the cession of the Pescadores Islands. The very first one of these was signed following a blockade of the Pearl River and concluded the First Opium War. These documents established spheres of influence for Russia, Germany, and other countries. For the point, identify these accords, such as Nanjing and Shimonoseki, named for their unfairness to China.", ANSWER: "unequal treaties"},
             {question: "2014.BBee.1 One of these wars involved French forces following the beheading of the missionary Auguste Chapdelaine; that war started when officials boarded the Arrow and lowered a British flag. The other of these wars was sparked in part by sailors killing a villager in the Kowloon incident. British victories in both of these wars resulted in the unequal Treaties of Nanjing and Tianjin. For the point, name these wars sparked by British interest in continuing to export a drug to China.", ANSWER: "Opium Wars"},
             {question: "2016.CBowl.8 One of these conflicts was triggered by the seizure of a ship believed to be held by pirates, the Arrow. Lin Zexu served as a naval commander during the first of these wars that ended with the Treaty of the (+) Bogue. Another of these wars was started by the Kowloon Incident. Their aftermath ended the (*) Canton System with the “unequal treaty” of Nanking. For ten points, name these 19th century wars fought in China over a drug processed from poppies.", ANSWER: "Opium Wars"},
             {question: "2016.NatsBowl.VFinal This city was the final port reached by Tome Pires, who traveled here with an expedition led by Fernão Pires de Andrade. An early insurance system called the Consoo Fund was set up in this city by its Cohong merchants. This city was home to the Thirteen Factories trade group. An open letter to Queen Victoria called foreigners in this city “barbarians” dealing poison, triggering a war that was ended by the Treaty of Nanjing, which let foreign merchants operate outside this city and ended the First Opium War. For ten points, name this southern Chinese city, the namesake of a Chinese dialect.", ANSWER: "Canton"},
             {question: "2016.NatsBee.4 In this country, Calvin Brice led an American Development Company that sought to build a railroad. The Burlingame Treaty amended an earlier treaty between this country and the United States. Under John Tyler, Caleb Cushing served as minister to this country; in that role, missionary Peter Parker served as chief translator. The US gained extraterritorial rights in this country after the Treaty of Wanghia. For the point, name this country which signed numerous unequal treaties with the United States and others after the Opium Wars.", ANSWER: "China"},
             {question: "2017.BBee.1 In this war’s Second Battle of Chuenpi, held at the mouth of the Humen Strait, the Nemesis became known as the devil ship. The second of these wars began with the seizure of the Arrow and resulted in several nations gaining most favored nation status. Commissioner Lin, the viceroy of Guangdong, began the first of these wars by dumping an illicit good into the port at Canton. For the point, name these wars fought between Britain and Qing Dynasty China over the namesake drug.", ANSWER: "Opium Wars"},
             {question: "2017.NatsBowl.7 During these conflicts, the Thirteen Factories were twice destroyed. James Bremer used gunboats to great effect in this conflict and blockaded the Pearl River. The second of these conflicts began when the Arrow was seized. Lin Zexu sent a letter asking 'where is your conscience?' to Queen Victoria in the first of these conflicts, which ended with the cessation of Hong Kong Island in the unequal Treaty of Nanking. For ten points, name this series of conflicts between Great Britain and China sparked by drug exports.", ANSWER: "Opium Wars"},
             {question: "2018.ABowl.9 The Battle of Yamen occurred in this southern province, where the Hong factories operated prior to the Opium Wars. The Pearl River Delta lies in this province, which borders the special administrative regions of Hong Kong and Macau. The most populous province in China is, for ten points, what region that contains a city once known as Canton?", ANSWER: "Guangdong"},
             {question: "2018.NatsBowl.10 In a major battle of this war, Sengge Renchen’s Mongolian cavalry charged at James Hope Grant’s forces at the Eight-Mile Bridge. An amphibious landing at Beitang helped one side in this conflict capture the Dagu forts. The USS San Jacinto was dispatched to capture the Barrier Forts during this conflict. The Treaties of Tianjin paused this war, which ultimately ended with Lord Elgin ordering the burning of the Summer Palaces. For ten points, name this war between the Qing government and a coalition of European forces, fought a decade after the initial war over narcotics trading.", ANSWER: "Second Opium War"},
             {question: "2019.NatsBowl.6 This city’s Thirteen Factories became integral to a trade monopoly run by the cohong guilds, which served this city’s namesake system. Lin Zexu’s attempt to destroy the opium trade in this city prompted Britain to send an expedition to nearby Hong Kong. The First Opium War was sparked in, for ten points, what coastal city that names a major Chinese dialect?", ANSWER: "Canton"},
             {question: "2012.NatsBowl.2 Zaiyi was one of the leaders of this movement. The Taiyuan Massacre occurred during it. The Seymour Expedition was an attempt to protect Western diplomats from this event, which was preceded by the failed Hundred Days Reform. The Eight-Nation Alliance was formed to suppress this rebellion. This event took place during the rule of the Empress Dowager Cixi and was carried out by the Society of Righteous and Harmonious Fists. For 10 points, name this revolt that attempted to force foreign influence out of China.", ANSWER: "Boxer Rebellion"},
             {question: "2014.BBee.4 The Ketteler Gate commemorates a German diplomat who was assassinated during this event. Zhang Zhidong (JONG ji-DONG) opposed an imperial edict relating to this event, and Yamagata Aritomo dispatched the largest contingent that quelled this revolt. It was encouraged by the Dowager Empress Cixi (SEE-shee). For the point, name this anti-westerner rebellion in China in 1900 that was led by the Society of Righteous and Harmonious Fists.", ANSWER: "Boxer Rebellion"},
             {question: "2014.ABowl.5 In the aftermath of this event, Herbert Quiers looted disturbed areas, an action denounced in the essay To the Person Sitting in Darkness by Mark Twain. As this movement was gaining strength, the Guangxu (gwang-SHOO) Emperor's Hundred Days' Reform ended. The Eight-Nation Alliance worked to suppress this event, which was initially supported by the Empress Dowager Cixi (SEE-shee). For 10 points, name this turn-of-the-twentieth century rebellion against imperialism in China.", ANSWER: "Boxer Rebellion"},
             {question: "2015.CBee.3 A powerful patron of this movement helped spark it by arresting the Guangxu (gwong- SHOO) Emperor. The Eight-Nation Alliance was sent to put down this movement, which resisted modernization efforts exemplified by the recent Hundred Days and Self-Strengthening movements. This movement was supported by Dowager Empress Cixi (pr. SEE-shee) and believed itself invulnerable to bullets. For the point, name this 1898 anti-foreigner uprising in China.", ANSWER: "Boxer Rebellion"},
             {question: "2016.BBowl.3 After 100 days of exercise and incantations, members of this non-American movement believed they gained invulnera- bility to bullets. Members of this movement sieged the Legation Quarter until the (+) Eight Nation Alliance freed them. This movement was supported until 1901 by the Dowager Empress (*) Cixi of the Qing [ching] Dynasty in hopes of ridding China of foreigners. For ten points, name this nationalist movement, also known as the Society of Righteous and Harmonious Fists.", ANSWER: "Boxers"},
             {question: "2017.BBee.1 German troops being sent to this event were commanded to “Show the old Prussian virtue” in the overtly imperialist “Hun Speech.” The murder of envoy Klemens von Kettler escalated this event, prompting the involvement of an Eight Nation Alliance. Frederick Ward was killed while leading the Ever Victorious Army during this event, paving the way for “Chinese” Gordon to take command. The Empress Dowager’s Qing government backed the Society of Righteous and Harmonious Fists in, for the point, what 1898 anti-foreigner uprising?", ANSWER: "Boxer Rebellion"},
             {question: "2018.BBee.3 After the losing side of this conflict was forced to pay 450 million silver taels in compensation, the “New Policies” were passed to boost tax revenue. Backlash against the Treaty of Tientsin helped prompt this conflict, in which a 55-day siege of the International Legations was ended by the arrival of the Eight Nation Alliance. The Empress Dowager Cixi       supported a militia group against foreign missionaries in, for the point, what Chinese rebellion led by the Society of Righteous and Harmonious Fists?", ANSWER: "Boxer Rebellion"},
             {question: "2018.ABee.1 After receiving news that diplomats had been tortured, French and British troops trashed this city’s Old Summer Palace in 1860. The Yongzheng Emperor required everyone taking the civil service examination to learn this city’s dialect of Mandarin. This city was the site of the Siege of the International Legations, which caused the deployment of the Eight Nation Alliance during the Boxer Rebellion. The Qing dynasty’s seat of power was the Forbidden City in, for the point, what capital of China?", ANSWER: "Beijing"},
             {question: "2019.ABee.Final This event’s perpetrators rose to prominence after attacking the Senluo Temple, causing its support to peak. Supporters of this event perpetrated the Juye Incident, in which missionary Richard Henle was murdered. This event included the siege of the Legations, which ended only when the Eight Nation Alliance was deployed. The New Policies were enacted by the Qing [ching] to address their failures during, for the point, what anti-foreigner rebellion that began in 1899 and was led by the Righteous and Harmonious Fists in China?", ANSWER: "Boxer Rebellion"},
             {question: "2018.ABee.Final A cartoon focusing on this policy titled “Putting his foot down” shows Uncle Sam declaring “you can’t divide Me.” Japan agreed to uphold this policy in the Lansing-Ishii Treaty, a weak agreement that was swiftly superseded by the Nine-Power Treaty. This policy was largely implemented by Secretary of State John Hay, who sought to preserve “territorial and administrative integrity.” For the point, name this American foreign policy meant to prevent “spheres of influence” over treaty ports and maintain a balance of international trade with China.", ANSWER: "Open Door Policy"},
             {question: "2019.ABowl.6 This policy was formulated in a memorandum authored by William Woodville Rockhill. The Nine-Power Treaty upheld this policy, which was issued as part of U.S. foreign policy in a namesake 1899 note. Elihu Root continued this policy, which was first implemented under his predecessor as Secretary of State. This policy was nearly abandoned after the Boxer Rebellion, which threatened to break this policy’s central nation into spheres of influences. For ten points, name this American policy aimed at keeping China’s economy accessible to all major powers.", ANSWER: "Open Door Policy"},
             {question: "2015.NatsBowl.5 This movement was inspired by a vision of a gold-bearded man with a sword and a seal, as well as a pamphlet called Benevolent Words to Inspire the World. This gender-segregated revolt was quashed in part by Zeng Guofan, and its Hakka-ethnicity founder believed he was the brother of Jesus. For 10 points, name this rebellion led by Hong (SHEE-oo-chew-AHN) Xiuquan that caused 20 million deaths in trying to form a Heavenly Kingdom of Great Peace in nineteenth-century China.", ANSWER: "Taiping Rebellion"},
             {question: "2014.ABee.1 Participants in this event foreswore the queue hairstyle and were accordingly called Longhairs. This event was prompted by a dream by a failed scholar instructing him to eradicate Earth's demons. It was put down by Chinese Gordon's Ever Victorious Army, ending the Heavenly Kingdom proposed by Hong Xiuquan (shee-KWAN). For the point, name this Chinese rebellion that was contempora- neous with the U.S. Civil War and caused about twenty million deaths.", ANSWER: "Taiping Rebellion"},
             {question: "2014.NatsBowl.2 A general in this conflict was a Hakka who gathered followers in his march from Guangzhou (gwang-JOE) to Guangxi (gwang-SHEE). Zeng Guofan's protege Li Hongzhang (HONG-jong) helped organize the mercenary armies on on side of this rebellion, which were led by Frederick Ward Townsend and Charles Gordon. The leader of this event was Hong Xiuquan (shee-KWAN), who claimed to be the younger brother of Jesus. For 10 points, name this rebellion against the Qing (CHING) in nineteenth-century China.", ANSWER: "Taiping Rebellion"},
             {question: "2015.NatsBee.Final This rebellion lost power after Yang Xiuqing's execution after he attempted to wrest control from its leader. This rebellion ended after forces under Zeng Guofan took Nanjing, which had been renamed Tianjing by this rebellion. Frederick Townsend Ward took part in fighting against this rebellion. This rebellion suffered defeats at the hands of Chinese Gordon and the Ever- Victorious Army. The leader of this rebellion joined the God Worshippers' Society and believed himself to be the younger brother of Jesus Christ. For the point, a Heavenly Kingdom was set up by Hong Xiuquan, the leader of what rebellion against the Qing dynasty?", ANSWER: "Taiping Rebellioin"},
             {question: "2017.CBowl.10 This rebellion was inspired by the pamphlet “Good Words for Exhorting the Age” and originated among the Hakka people. The Ever Victorious Army was essential in putting down this rebellion under the leadership of General Gordon, who gained a nickname from that campaign. This rebellion’s leader, a man who claimed to be the younger brother of Jesus, was found dead in his palace in Nanjing. For ten points, name this 19th century rebellion, led by Hong Xiuquan, that tried to establish a Heavenly Kingdom in China.", ANSWER: "Taiping Rebellion"},
             {question: "2017.NatsBee.Playoff1 This event began when one side displayed the Iron Blood flag before winning the Battle of Yangxia. A revolt over the Railway Protection Movement led to the Wuchang Uprising, which was the start of this event. This (+) revolution led to the creation of the Beiyang Government and the Five-Colored Flag. After this event, Yuan (*) Shikai declared himself emperor in conflict with Sun Yat-Sen’s KMT. For the points, name this event that led to the founding of the Republic of China and the abdication of Puyi, the last Emperor of China.", ANSWER: "Xinhai Revolution"},
             {question: "2018.NatsBee.VFinal The anniversary of this event is commemorated as Double Ten Day. The mishandling of the Railway Protection movement sparked this event and culminated in the Battle of Yangxia. The forces of the Tongmenghui played a key role in this event, which began with the (+) Wuchang Uprising. Yuan Shikai used the Beiyang Army to become provisional (*) President during this event and forced the abdication of Emperor Puyi. For the points, name this revolution led by Sun Yat-Sen which ended the Qing Dynasty and led to the establishment of the Republic of China.", ANSWER: "Xinhai Revolution"},
             {question: "2016.NatsBowl.VQuarterfinals This leader allied with Prince Gong and Prince Chun in the Xinyou  Coup to defeat Sushun and the Eight Regent Ministers. This ruler ordered Zeng Guofan to quell a rebellion, and helped appoint Zaitian to replace Tongzhi after he died. This figure was accused of embezzling naval funds to build a Marble Boat for the Summer Palace, and also quashed the Hundred Days’ Reform while ruling on behalf of the Guangxu Emperor. This ruler was defeated by the Eight Nation Alliance after encouraging the army to support the Boxer Rebellion. For ten points, name this Dowager Empress of the Qing Dynasty.", ANSWER: "Cixi"},
             {question: "2017.NatsBowl.1 This leader was able to outmaneuver a group of eight regents led by Sushun to seize power and empowered the Grand Council to make most decisions. In 1898, this leader carried out a coup that ended the Hundred Days’ Reform. This leader agreed to the Self-Strengthening Movement proposed by Prince Gong, but later caused an invasion by an alliance of Western powers due to her support for the Boxer Rebellion. For ten points, name this anti-Westernizing Empress Dowager during the late Qing Dynasty.", ANSWER: "Cixi"},
             {question: "2014.NatsBee.Final This leader chose his wife after looking at four photographs, but was asked to make a second selection because his first choice was too poor. The Articles of Favorable Treatment were made to protect this man, although they were later revised, causing him to be forced out of his home. Following Japanese occupation of parts of his country, this man was made the Kangde Emperor of Manchukuo. Earlier, he ruled as a child for four years until the Xinhai (SHIN-hai) Revolution forced him to abdicate. For the point, name this final emperor of the Qing (CHING) dynasty and China.", ANSWER: "Puyi"},
             {question: "2019.ABowl.8 This man was briefly restored to power by Zhang Xun. This man benefited from the Articles of Favourable Treatment, though that was revised following a coup by Feng Yuxiang. Prince Zaifeng ruled as a regent for this man, who was tutored in his early years by Reginald Johnston. This man, who was forced to abdicate at age 6, was the subject of a Bernardo Bertolucci biopic that detailed his path from Cixi’s successor to puppet leader of Manchukuo. For ten points, name this final emperor of China.", ANSWER: "Puyi"},
             {question: "2018.ABee.Final The National Protection War targeted this man due to his plan to reinstate the monarchy. In 1895, this man was given control of the Pacification Army and transformed it into the modernized New Armies. This man named himself the Hongxian Emperor, but his 1916 death ended his empire and ushered in the Warlord Era. This man negotiated an end to the Xinhai Revolution and the abdication of Puyi as the last Qing prime minister. For the point, name this Chinese general who, upon the resignation of interim president Sun Yat-Sen, became the first official leader of the Republic of China.", ANSWER: "Yuan Shikai"},
             {question: "2013.NatsBowl.15 The leader of this region had the reign title of Kangde. The northern border of this state was the bone of contention in the Battle of Khalkhin Gol. It was created following actions by the Kwantung Army that were not approved by the civilian authorities under Prime Minister Reijiro. This state was established following the Mukden Incident and was a member of the Greater East Asia Co-Prosperity Sphere. The figurehead leader of this state was the former emperor Henry Puyi. For 10 points, name this puppet state created by Japan in 1932 in northeastern China.", ANSWER: "Manchukuo"},
             {question: "2015.NatsBowl.7 The only political party formed in this polity was the Concordia Association. A border dispute between this polity and a western neighbor led to the Battle of Khalkhin-Gol. Unit 731 carried out inhumane experiments in this state. The Lytton Report investigated an incident that led to its creation. This state was established after the Mukden Incident, and installed Puyi as Emperor. For 10 points, name this puppet state set up after Japan's invasion of Manchuria.", ANSWER: "Manchukuo"},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
];
