var array = [{question: "2011.NatsBowl.1 Prior to this battle, one side opened up a key supply route called the Cracker Line and defeated an enemy force at Wauhatchie. During its beginning, General George Thomas was able to quickly take Orchard Knob. In the aftermath of this battle, Joseph Johnston replaced Braxton Bragg as the head of a large army. Lookout Mountain and (*) Missionary Ridge were two defensive structures during this battle whose aftermath saw an assault on Atlanta. For 10 points, name this November 1863 battle of the American Civil War fought several months after the Battle of Chickamagua, a Union victory in southeastern Tennessee.", ANSWER: "Chattanooga"},
             {question: "2011.NatsBowl.3 Because he was delayed in the Battle of Rosebud, George Crook could not participate in this battle. Frederick Benteen provided backup for Marcus Reno on what is now known as Reno Hill during this battle. One of the few survivors on the losing side of this battle was named Curly, and his report of this battle differs from that of Chief Gall. (*) Buffalo Calf Road Woman is credited with knocking the American commander off his horse. This 1876 battle of the Great Sioux War resulted in a decisive victory for the side led by Crazy Horse. For 10 points, name this battle nicknamed “Custer’s Last Stand.”", ANSWER: "Little Bighorn"},
             {question: "2011.NatsBowl.5 Jacklyn Lucas became the youngest man since the Civil War to receive a Medal of Honor for his heroism in this battle. During this battle, the Bismarck Sea was sunk during a kamikaze attack. Men like Ira Hayes and John Bradley became famous for their participation in this battle thanks to (+) Joe Rosenthal. Ground fighting during this battle was prolonged due to Tadamichi Kuribayashi prohibiting banzai charges, and that commander also ordered an extensive series of tunnels to be dug. Some of the heaviest fighting in this battle took place on Meatgrinder Hill and Mount (*) Suribachi. For 10 points, name this early 1945 battle in the Pacific Theatre of World War II on a “God-forsaken island”, where several Marines famously raised a US flag.", ANSWER: "Iwo Jima"},
             {question: "2011.NatsBowl.9 One supply line in this battle came to be known as the Sacred Way for its use in this battle. A costly strategic blow to one side in this battle was the loss of Fort Douaumont. The French were ultimately able to reclaim that fort under the leadership of Philippe Petain, though its loss had resulted in 100,000 casualties. For 10 points, name this bloody battle of World War I that ran from February to December of 1916.", ANSWER: "Verdun"},
             {question: "2011.NatsBowl.11 Seven years before this battle, the death of Yohannes IV led to one participant helping the forces of Shewa to take the throne. This battle settled a conflict that began due to Prime Minister Crispi’s interpretation of Article Seventeen of the Treaty of Wichale. Oreste Bartieri lost to Menelik II and made peace at the Treaty of Addis Ababa following, for 10 points, what 1896 battle in which Ethiopia turned back an Italian force?", ANSWER: "Adowa"},
             {question: "2011.NatsBowl.11 The brother of one man killed at this battle was named Tostig, and himself was killed weeks before this battle. One force in this battle was initially deployed on Senlac Hill, and one battle that preceded this one was at (+) Gate Fulford, while another took place north of the site of this battle and featured an invading force led by Harald Hardraada of Norway. That battle, Stamford Bridge, had weakened one side in this conflict, who were led by (*) Harold Godwinson, and this battle is famously depicted by the Bayeux Tapestry. For 10 points, name this 1066 battle in which Harold's English force was defeated by the Norman army of William the Conqueror.", ANSWER: "Hastings"},
             {question: "2011.NatsBowl.12 One side in this battle was supplied in part by a group of troops who ran the Red Ball Express. An offensive launched by the other side in this battle was Operation Bodenplatte, and that side in this battle also launched a surprise attack on the ghost front. For 10 points, name this 1944-1945 battle fought in the Ardennes Mountains, in which the Germans were ultimately repulsed despite causing a temporary namesake deformation in the Allied line.", ANSWER: "Bulge"},
             {question: "2011.NatsBowl.12 In this battle, the Duke of Brabant arrived late from a christening and was killed because he hastily made an unrecognizable tabard from a flag. The winner ordered his men to lance their prisoners at the end of this battle, which was preceded by the siege of Harfleur. The losers managed to steal a crown from the baggage train of one of the victors before their commander, (*) Charles d'Albert, led them headlong into a line of pikes driven into the deep mud. The superiority of the Welsh longbow was also critical to the success of Henry V. Fought in 1415 on St. Crispin's Day, for 10 points, name this turning point of the Hundred Years' War.", ANSWER: "Agincourt"},
             {question: "2011.NatsBowl.18 This battle led to a treaty that was signed in the palace of Bratislava, the Peace of Pressburg. The turning point of this battle came when the attackers captured the Pratzen Heights. This battle led to the dissolution of the Holy Roman Empire. For 10 points, name this December 1805 battle in which Napoleon divided his army against a larger force and still beat the combined forces of Russia and Austria.", ANSWER: "Austerlitz"},
             {question: "2011.CBowl.6 One force at this battle organized in a formation similar to a phalanx that had densely wooded forests on each of their flanks. The cavalry of the opposing side in this battle returned to their camp after a rumor about looting treasure from Bordeaux. The Umayyads at this battle were commanded by Abd al-Rahman. For 10 points, name this 732 battle where Charles Martel halted Muslim expansion in Europe.", ANSWER: "Tours"},
             {question: "2011.CBowl.10 The outcome of this battle was made possible by the comte de Grasse's victory in the Battle of the Chesapeake, which made the British unable to lift the siege led by Rochambeau and Washington. For 10 points, name this last major battle of the Revolutionary War that saw Cornwallis surrender to Washington.", ANSWER: "Yorktown"},
             {question: "2011.CBowl.10 Immediately before this battle, William Halsey suffered a bout of psoriasis, leading him to be replaced by Raymond A. Spruance. The JN-25 code was broken before this battle, during which the Enterprise and Hornet emerged victorious over the Kaga and Akagi. For 10 points, name this 1942 allied naval victory in World War II.", ANSWER: "Midway"},
             {question: "2011.CBowl.10 In this battle, Joshua Chamberlain’s Maine infantry led a bayonet charge at Little Round Top.(+) The end of this battle came shortly after the failure of a charge on Cemetery Ridge (*) led by George Pickett. For 10 points, name this three day 1863 battle in Pennsylvania often considered the “high water mark” of the Confederacy.", ANSWER: "Gettysburg"},
             {question: "2011.CBee.1 This battle was preceded by fighting at Quatre-Bras and Ligny. During this battle, the farm of Le Haye Sainte was captured by Marshall Ney, and the arrival of Prussian troops under von Blucher secured victory for the Duke of Wellington’s forces. This battle marked the end of the Hundred Days. For the point, name this final defeat of Napoleon.", ANSWER: "Waterloo"},
             {question: "2011.CBee.2 Light infantry commander Lord Balcarres surrendered during this battle. One of Daniel Morgan's snipers killed Simon Fraser during this battle. A British victory at Freeman's Farm was undone by their loss at Bemis Heights here. For the point, name this Revolutionary War battle that saw the defeat of John Burgoyne by Horatio Gates and Benedict Arnold.", ANSWER: "Saratoga"},
             {question: "2011.CBee.2 Before this battle, the winners cracked the JN-25 code. The Hornet sunk the Mikuma in this battle, during which the Hiryu airplanes sunk the USS Yorktown. It occurred a month after the Battle of Coral Sea. For the point, name this decisive battle of the Pacific Theater of World War II, fought near a namesake atoll.", ANSWER: "Midway"},
             {question: "2011.BBowl.2 Sites during this battle included Freeman's Farm and Bemis Heights. During this battle, forces under Horatio Gates and Benedict Arnold forced the surrender of John Burgoyne. For 10 points, name this revolutionary campaign in New York, an American victory that brought France into the war.", ANSWER: "Saratoga"},
             {question: "2011.BBowl.8 This battle's location is now combined with Des Braves Park as Battlefields Park. This battle was the first major engagement following the fall of Louisbourg. Both the Marquis de Montcalm and General James Wolfe died during this battle on the Plains of Abraham. For 10 points, name this 1759 British victory that led to the capture of Montreal.", ANSWER: "Quebec"},
             {question: "2011.BBee.2 This battle was preceded by the Battle of Lake Borgne, in which Alexander Cochrane led his fleet to the city of this battle. Jean Lafitte's pirates helped the winning side in this battle. General Edward Pakenham died during this battle. For the point, name this battle that occurred after the official end of the War of 1812, a victory for Andrew Jackson.", ANSWER: "New Orleans"},
             {question: "2011.BBee.2 Prior to this battle's end, Albert Martin led thirty-two men from DeWitt Colony to aid one side. That side in this battle was led by William Travis, who fought with a force that included James Bowie and Davy Crockett. For the point, name this 1836 battle in which the Mexican force under Santa Anna wiped out the defenders of a San Antonio mission.", ANSWER: "Alamo"},
             {question: "2011.BBee.3 This battle saw one side attempt the Sinyavino Offensive, which threw off the timing of their enemies, who were at the time planning Operation Nordlicht. This battle saw a Road of Life of supplies ferried across Lake Ladoga. For the point, name this World War II battle that was a lengthy siege of a Russian city now known as St. Petersburg.", ANSWER: "Leningrad"},
             {question: "2011.BBee.4 The losing general in this battle split forces under Frederick Benteen and Marcus Reno from the main army. A horse named Comanche was the only survivor on one side of this battle, in which five companies of the Seventh Cavalry was lost. For the point, name this 1876 battle in which the Lakota Sioux under Sitting Bull ensured George Custer's Last Stand.", ANSWER: "Little Bighorn"},
             {question: "2011.BBee.5 The losers in this battle were weakened by winning the Battle of Stamford Bridge a few weeks prior. This battle actually occurred at Senlac Hill. The Bayeux Tapestry is a depiction of this battle, which ended with Harold Godwinson's death. For the point, name this battle that occurred in 1066 and allowed William the Conqueror to become King of England.", ANSWER: "Hastings"},
             {question: "2011.BBee.5 Nathanael Greene's defeat at Guilford Court House directly led to this battle. Admiral de Grasse's defeat of the British Navy and blockade of the Chesapeake Bay was critical to the American victory in this battle. For the point, name this last major battle of the Revolutionary War in which Lord Cornwallis surrendered to George Washington.", ANSWER: "Yorktown"},
             {question: "2011.ABowl.1 Prior to this battle, George Crook's men had been surprised and defeated at the Battle of the Rosebud. This battle's outset saw the charge of Marcus Reno turn into a rout when his left flank was turned by forces under Gall. That force was only saved by reinforcements under Frederick Bendeen. This battle ended with five companies of the Seventh Cavalry being completely destroyed. For 10 points, name this 1876 battle that saw Sitting Bull and Crazy Horse's Sioux and Cheyenne force annihilate forces under George Custer.", ANSWER: "Little Bighorn"},
             {question: "2011.ABowl.1 In the aftermath of this battle, Uluch Ali managed to salvage most of his forces from harm. Miguel de Cervantes lost use of an arm during this battle. During this battle, the half-brother of Philip II, Don John of Austria, commanded the forces of the Holy League. For 10 points, name this 1571 naval battle which ended Ottoman dominance in the Mediterranean.", ANSWER: "Lepanto"},
             {question: "2011.ABowl.3 In this battle, Joseph Hooker's corps was unable to capture Dunker Church. After Burnside captured a stone bridge, A.P. Hill arrived with reinforcements from (+) Harpers Ferry, ending this battle. Fighting also occurred on a sunken road called Bloody Lane during this battle, before which the Union discovered Special Order 191, part of the Confederate plans, wrapped around some cigars. (*) McClellan's failure to pursue the Confederates after this battle led to his removal from command. The outcome of this battle led Lincoln to issue the Emancipation Proclamation. For 10 points, name this bloodiest day of the Civil War, an 1862 battle in Maryland.", ANSWER: "Antietam"},
             {question: "2011.ABowl.4 During this battle, a farmhouse called La Haye Sainte was captured by the Old Guard commander Michel Ney. The losing side's right flank was attacked at this battle by Gebhard von Bluecher, ultimately leading to the defeated commander's exile to Saint Helena. For 10 points, name this 1815 battle in which Napoleon was defeated by the Duke of Wellington.", ANSWER: "Waterloo"},
             {question: "2011.ABowl.4 The leader of one side in this battle agreed to a request made by Cardinal Talleyrand to hold his troops back on a Sunday. That leader, Jean le Bon, followed the advice of William Douglas to fight on foot, and was captured in this battle by forces under Edward, the Black Prince. For 10 points, name this 1356 victory for the English in the Hundred Years' War.", ANSWER: "Poitiers"},
             {question: "2011.ABowl.4 One site at this battle was held after a bayonet charge by the Twentieth Maine, which was led by Joshua Chamberlain. This battle saw a futile march under heavy fire occur during an attack on Cemetery Ridge called Pickett’s Charge. For 10 points, name this three day 1863 battle in which Robert E. Lee’s invasion was stopped by George Meade in Pennsylvania.", ANSWER: "Gettysburg"},
             {question: "2011.ABowl.5 One rail fence in this battle was held for a time by four hundred militia commanded by John Stark. One side landed for this battle at Moulton's Point, and this battle saw the death of Joseph Warren. William Prescott and Israel Putnam, the losing commanders of this battle, have both been credited with ordering, don't fire until you see the whites of their eyes. For 10 points, name this 1775 strategic loss but moral victory for the U.S. fought on Breeds Hill near Boston.", ANSWER: "Bunker Hill"},
             {question: "2011.ABowl.7 One side in this battle landed at Pevensey before moving to this battle's site. This battle took place in Battle, seven miles from its namesake town. Before this battle, its first casualty, the bard Taillefer, juggled swords and sang the Song of Roland. One side in this battle was on Senlac Hill, and had won against Harald Hardrada at Stamford Bridge. This battle is depicted in the Bayeux Tapestry. For 10 points, name this 1066 loss for Harold Godwinson during William the Conqueror's Norman invasion of England.", ANSWER: "Hastings"},
             {question: "2011.ABowl.8 One commander at this battle, Henry Percy, refused to move his forces when signaled, and another leader of forces for that side was John Howard. Thomas and William Stanley initially remained unengaged at this battle, but encircled and killed Richard III, leaving Henry Tudor the victor. For 10 points, name this battle that closed the Wars of the Roses.", ANSWER: "Bosworth Field"},
             {question: "2011.ABee.2 During this battle, the Comte de Grasse prevented a relief effort by Thomas Graves by defeating him at the Battle of the Chesapeake. This battle’s victors had marched down from New York to besiege a general retreating from North Carolina after the Battle of Guilford Courthouse. The defeated force’s band played “The World Turned Upside Down” while surrendering at this battle. For the point, name this defeat for Lord Cornwallis which ended the Revolutionary War.", ANSWER: "Yorktown"},
             {question: "2011.ABee.3 The first part of this battle was fought at Freeman's Farm. Later fighting as part of this battle was fought at Bemis Heights and led to the defeat of a General who had waited for eighteen days before this battle to allow his lengthy baggage train to meet his forces. News of this battle led Louis XVI to negotiate a French alliance with the victorious colonists. For the point, name this 1777 battle in upstate New York.", ANSWER: "Saratoga"},
             {question: "2011.ABee.4 The Battles of Wavre and Ligny were two battles that preceded this battle. One commander at this battle formed up his men on Mont Saint-Jean ridge to prevent access to Belgium. The French commander at this battle sent his younger brother Jerome to attack the farm house of Hougoumont which anchored the British right flank. The turn of this battle was when the Prussian army arrived to relieve the faltering British soldiers under the Duke of Wellington. For the point, name this final defeat for Napoleon.", ANSWER: "Waterloo"},
             {question: "2011.ABee.4 An attempt to conclude this battle ended when the Italian 8th Army was defeated, threatening Erich von Manstein’s flank. The turning point at this battle came with the launching of Operation Uranus, which encircled the attackers in this battle. An attempt to supply those attackers by air was only able to provide them with starvation rations and the promotion of Friedrich Paulus to Field Marshal was unable to prevent him from surrendering the 9th Army the next day. For the point, name this 1942-43 battle, the siege of a Russian city considered a major turning point of World War II.", ANSWER: "Stalingrad"},
             {question: "2011.ABee.4 This battle’s victors marched to it a month after besieging Harfleur. The Treaty of Troyes was signed after this battle, in which a row of sharpened wooden stakes planted in the mud protected against cavalry charge so that Thomas Erpingham’s longbowmen could fire. Charles d’Albret was killed commanding the losing side of this battle, which took place on Saint Crispin’s Day. For the point, name this 1415 victory of Henry V of England over the French.", ANSWER: "Agincourt"},
             {question: "2012.NatsBowl.5 One commander in this battle famously proclaimed, We are in the chamber pot and about to be shat upon. General Ducrot took command partway through this battle, but his order to retreat was overruled by General de Wimpffen. This battle was preceded by the Battle of Beaumont and a failure to lift the Siege of (+) Metz. Moltke the Elder split his forces into three groups, allowing him to encircle the opposing army. Patrice de MacMahon led the Army of Chalons to defeat in this battle. (*) Napoleon III was captured as a result of this battle, thereby effectively deciding the war in favor of Prussia. For 10 points, name this 1870 battle of the Franco-Prussian War.", ANSWER: "Sedan"},
             {question: "2012.NatsBowl.7 One noble at this battle, the Earl of Northumberland, chose not to aid his king at a critical moment. The intervention of Thomas and William Stanley was critical in this battle, in which Richard of York was killed, marking the end of the Plantagenet dynasty. For 10 points, identify this battle at which Henry Tudor was victorious, ending the Wars of the Roses.", ANSWER: "Bosworth Field"},
             {question: "2012.NatsBowl.9 Notable combatants in this battle included the future Hero of Bennington, John Stark, and Daniel Shays. John Trumbull commemorated the Death of General Warren at this battle, in which the British won a Pyrrhic victory by gaining the (+) Charlestown peninsula at the expense of numerous officers and a third of their forces. Occurring on July 17, 1775 during the Siege of (*) Boston, the majority of the fighting in it actually occurred on Breed's Hill. For 10 points, name this battle of the American Revolution during which either Israel Putnam or William Prescott saying, Don't fire until you see the whites of their eyes.", ANSWER: "Bunker Hill"},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
             {question: "", ANSWER: ""},
];
