var myArray = ['Two weeks after a Robert Geiger news story coined a name for this event, Hugh Bennett was made director of a new agency within the Interior Department. This event prompted the Soil Conservation Act, as it was partly caused by cattle overgrazing. Dorothea Lange’s iconic photograph Migrant Mother depicts a family during, for ten points, what event in which "Okies" attempted to move to California to avoid severe drought during the Great Depression?                                                                                                                              ANSWER: Dust Bowl', 
               'Genseric captured this city after his betrothal to Eudocia was broken, and Alaric was able to capture this city after the death of Stilicho. The Battle of the Allia led to the capture of this city, which was forced to measure out ransom money using weighted scales by Brennus. Romulus Augustulus was deposed after the capture of this city in 476 AD. For ten points, name this city that was sacked several times during the fall of its Italy-based empire.                                                                                                                               ANSWER: Rome',
               'This kingdom was briefly controlled by Britain after the arrival of the HMS Carysfort in the Paulet Affair. Because Kalakaua had been intimidated into giving his power away, this kingdom’s legal code was known as the Bayonet Constitution. Sanford Dole was appointed president of this kingdom shortly before it was annexed by William McKinley in 1898. For ten points, name this kingdom, that was ruled by Queen Liliuokalani and became the 50th US state.                                                                                                                               ANSWER: Kingdom of Hawai’i',
               'In what became known as this city’s "mile," a group of troops including Randall Ramaglia walked through RPG fire to a rally point at National Street. William Garrison commanded troops in a battle in this city that was part of the larger Operation Gothic Serpent; in that battle, troops under Mohammad Farah Aidid shot down two Black Hawk helicopters. For ten points, name this site of a 1993 battle involving Delta Force, the capital of Somalia.                                                                                                                               ANSWER: Mogadishu',
               'This leader’s promotion of pro-feminist policies was noted with the statement, "Women hold up half the sky." This man began the Anti-Rightist Campaign after severe criticism led him to undo the Hundred Flowers Movement. In a failed attempt to modernize, this man encouraged peasants to create backyard furnaces during the Great Leap Forward, which began in 1958. For ten points, name this Communist chairman of China.                                                                                                                               ANSWER: Mao',
               'This President’s doctrine pledged support to Middle Eastern governments, including military support for Camille Chamoun of Lebanon. Earl Warren was appointed as Chief Justice by this president a year before Brown v. Board of Education overturned the doctrine of "separate but equal." This president sent members of 101st Airborne Division to escort the Little Rock Nine. For ten points, name this president and former World War II Supreme Allied Commander.                                                                                                                               ANSWER: Eisenhower',
               'Members of this religious movement follow a ruleset called the Ordnung. One of the most conservative sects of this religious group, based in Nebraska, is known for its brown clothing. Some young people from this religious group are allowed to disobey norms in an exploratory period called Rumspringa. Lancaster County, Pennsylvania was a migration site for many members of, for ten points, what religious group known for living without the conveniences of modern technology?                                                                                                                               ANSWER: the Amish',
               'In this work, a character recounts the tale of a man named Er who revives on his funeral pyre and shares an account of the afterlife. A character in this work tries to explain the psyche by asking Glaucon to imagine a divided line and imagines a ring that makes the wearer invisible, the Ring of Gyges. The Allegory of the Cave and the benefits of rule under a "philosopher-king" are described in, for ten points, what Platonic dialogue about justice and forms of government like oligarchy and democracy?                                                                                                                               ANSWER: The Republic',
               'The "United Empire" faction of these people consisted of members who migrated to Canadian provinces. These people were led into combat by Patrick Ferguson, where they were defeated at Kings Mountain. A considerable population of North and South Carolina consisted of these people, whom Charles Cornwallis hoped to gain the support of during his campaign there. For ten points, give this term for American colonists who supported Great Britain during the Revolution.                                                                                                                               ANSWER: Loyalists',
               'This battle was fought concurrently with an engagement at Wavre [wahv], leading to the absence of Emmanuel Grouchy. This battle is commemorated by the Lion’s Mound, where a commander was shot off his horse. The arrival of Gebhard von Blucher’s Prussians helped turn the tide of this battle, which ended the Hundred Days and forced its loser into exile in St. Helena. For ten points, name this 1815 battle in which Wellington defeated Napoleon for the last time.                                                                                                                               ANSWER: Battle of Waterloo'
               'This dynasty was challenged by followers of the Celestial Masters, who launched the Five Pecks of Rice rebellion. Sima Qian [CHEE-an] compiled the Records of the Grand Historian under this dynasty, which became the rst to use the civil service examination and linked itself to Rome using an overland trade route. For ten points, name this ancient dynasty that shares a name with the majority ethnic group of China.‘ANSWER: Han Dynasty',
'Greer County eventually was ruled to be part of this state after a dispute over the Adams-Onis Treaty with its southern neighbor. This state was assigned the Cimarron Territory in 1890 but was considered No Man‘s Land beforehand. The Unassigned Areas in this state were allocated by an 1889 land rush in which the “Sooners" rushed across the border. For ten points, name this US state who has had several territorial disputes with its southern neighbor, Texas.ANSWER: Oklahoma',
'During a revolt named for this city, Eduard Goldstucker and the Writers Union went on television in an attempt to test free press laws. That revolt began when Jan Palach set himself on re in this city‘s Wenceslas Square. Alexander Dubcek [doob-check] implemented “socialism with a human face" as part of a period of liberalization in 1968 known as this city‘s “Spring." Soviet tanks eventually rolled into, for ten points, what capital city of Czechoslovakia?ANSWER: Prague (accept Prague Spring)',
'This man was assaulted by Frankie Gallucio while working at the Harvard Inn under his mentor Frankie Yale. The “Untouchables" were created by Eliot Ness to counter this man, who was the rst criminal to be labeled “Public Enemy Number One." An attack that was probably ordered by this man targeted Bugs Moran and his Northside Gang. Tax evasion was the ultimate downfall of, for ten points, what Chicago gangster known as “Scarface?"ANSWER: Al Capone',
'This ruler attempted to protect shipping from British warships by forming the League of Armed Neutrality. This ruler‘s conquests were con rmed in the Treaty of Kuchuk-Kainarji, cementing the end of the Crimean Khanate. Three partitions of Poland were overseen by this ruler, who took power after her lover Grigory Orlov helped overthrow Peter III. For ten points, name this enlightened tsarina of Russia.ANSWER: Catherine the Great (accept Catherine II)',
'The masses of these entities are governed by the whole number rule as described by Francis Aston, whose cousin Margaret Todd suggested a name for these entities from the Greek for “at the same place." One of the 15 of these entities for carbon is used in radioactive dating, has a half-life of 5,700 years, and has eight neutrons instead of the more stable six-neutron form. For ten points, give this term for variants of the same element that have different atomic masses.ANSWER: isotopes','‘This politician promised “No more appeasement" during an event known as “Bloody Thursday," in which he called in the National Guard to put down student protests at Berkeley. This politician, who signed the Therapeutic Abortion Act as governor, supported Barry Goldwater in his “A Time for Choosing" speech at the 1964 RNC. For ten points, name this Republican politician who was elected President in 1980.ANSWER: Ronald Reagan',
'In 1975, the CIA made estimates on this country‘s military e orts by counting the number of baseball diamonds built in Angola. Similarly, in 1970, the presence of a soccer eld instead of baseball diamonds on Cazo Alcatraz in this country‘s port of Cienfuegos suggested to the CIA that the Soviet Union, not this country, was building naval infrastructure here. For ten points, name this country that hosted a set of Soviet-deployed missiles in 1962, leading to a namesake “crisis."ANSWER: Cuba',
'A ray of sunlight hit the casket of Winston Churchill as this song was being performed at his funeral. This song describes a gure who is seen “in the watch res of a hundred circling camps." This song, which was rst published in the (+) Atlantic Monthly in 1862, inspired the title of Steinbeck‘s The Grapes of Wrath. The music of (*) “John Brown‘s Body" was used for, for ten points, what patriotic song by Julia Ward Howe that begins with the line “Mine eyes have seen the glory of the coming of the Lord"?ANSWER: The Battle Hymn of the Republic',
'This politician‘s constitutional authority was the subject of the Humble Petition and Advice. This gure‘s massacre of civilians during the siege of (+) Drogheda [drow-duh] led him to be reviled in Ireland. This man and his son-in-law, Henry Ireton, commanded the left and right wings of Thomas Fairfax‘s (*) New Model Army during a victory at Naseby. For ten points, name this Lord Protector of England following the English Civil War.ANSWER: Oliver Cromwell',
'This territory‘s Governor Charles Robinson opposed the expansion of slavery as promoted by its Lecompton Constitution. Several settlers were killed in this territory at Pottawatomie by (+) John Brown in retribution for the sacking of its town of Lawrence; that sacking was a response to Charles Sumner‘s beating for denounced the pro-slavery (*) “crime" against this territory. For ten points, name this territory that was “bleeding" over slavery in the 1850s and whose early Topeka Constitution banned slavery.ANSWER: Kansas (accept Bleeding Kansas)',
'Leaders of this nation derived their title from the phrase “tent government." One leader of this nation won a battle through the ingenious use of arquebuses to puncture the armor of cavalry; his ally would win the Battle of (+) Sekigahara to take control of this nation and form a bakufu. Matthew (*) Perry‘s black ships forced this nation to sign a treaty with the U.S., ending its isolationism. For ten points, name this country ruled by Oda Nobunaga and Tokugawa Ieyasu.ANSWER: Japan (accept Nippon or Nihon)',
'In 1997, Borge Ousland completed a solo, kite-aided journey across this region. In December 2018, Colin O‘Brady completed a 921-mile journey across this region, nishing with a stretch of 32 hours without sleep. The Nimrod (+) expedition attempted a journey in this region, where it was based in McMurdo Sound. In 1915, Sir Ernest Shackleton lost the Endurance in an (*) ice flow while exploring, for ten points, what continent where Roald Amundsen led the rst party to reach the South Pole?ANSWER: Antarctica (accept South Pole until “continent" is mentioned)',
];
    var rand = myArray[Math.floor(Math.random() * myArray.length)];
    var i = 0;
    var speed = 60;
function typeWriter() {
  if (i < rand.length) {
    document.getElementById("question").innerHTML += rand.charAt(i);
    i++;
    setTimeout(typeWriter, speed);
  }
}
