var answers = [
     'Dust Bowl',
     'Rome',
     'Hawaii',
     'Mogadishu',
     'Mao Zedong',
     'Eisenhower',
     'Amish',
     'The Republic',
     'Battle of Waterloo',
     'Martin Luther',
     'Korea',
     'Eisenhower',
     'Snake River',
     'Ebola',
     'Osiris',
     'Dvorak',
     'America',
     'Chinese Communist Party',
     'Hull House',
];
