var answers = ['Dust Bowl',
     'Rome',
     'Hawaii',
     'Mogadishu',
     'Mao Zedong',
     'Eisenhower',
     'Amish',
     'The Republic',
     'Battle of Waterloo',
/*C-Set Bowl 2015-16, Round 1*/'Martin Luther',
     'Korea',
     'Eisenhower',
     'Snake River',
     'Ebola',
     'Osiris',
     'Dvorak',
     'USA',
     'Chinese Communist Party',
     'Hull House',
     'Argentina',
     'Tomb of King Tut',
     'Genocide',
     'Mount Everest',
     'Sikhism',
     'Pericles',
     'Florida',
     'Uruguay',
     'Sputnik',
     'Rush Limbaugh',
     'Francis Scott Key',
     'Spanish Civil War',
     'New York City',
     'Texas',
     'Rupert Murdoch',
     'Justinian',
     'Portugal',
/*C-Set Bowl 2015-16, Round 2*/'Wilson',
     'Tale of Two Cities',
     'Bunker Hill',
     'Tubman',
     'Romulus',
     'Henry',
     'Tierra del Fuego',
     'Guernica',
     'Clooney',
     'Ivan the Terrible',
     'Demand',
     'East Germany',
     'D Day',
     'Halley’s Comet',
     'Triangle Shirtwaist',
     'Detroit',
     'Edward I',
     'Great Wall',
     'Missouri Compromise',
     'Snowden',
     'Paine',
     'Conservative',
     'Second Punic War',
     'China',
     'Assassination of JFK',
     'Venice',
     'Mali Empire',
/*C-Set Bowl 2015-16 Round 3*/'Congress of Vienna',
     'Mayflower Compact',
     'Abe',
     'Pershing',
     'Yangtze',
     'sleep deprivation',
     'John Brown',
     'Isabella I',
     'Charles de Gaulle',
     'columns',
     'Alexander the Great',
     'Alcatraz',
     'diamonds',
     'Indiana',
     'Vikings',
     'Red Badge of Courage',
     'tsars',
     'Chernobyl',
     'John Rolfe',
     'Volkswagen',
     'wine',
     'Russian Navy',
     'Camp David Accords',
     'Durer',
     'Manson',
     'Elizabeth I',
     'Native Americans',
/*C-Set Bowl 2015-16 Round 4*/'Archimedes',
     'Bacon Rebellion',
     'Midway',
     'Edison',
     'circulatory',
     'League of Nations',
     'Mozart',
     'Super Bowl ring',
     'Salem Witch Trials',
     'Borgia',
     'Palestine',
     'Manhattan',
     'Dalai Lama',
     'Holy Roman Emperor',
     'Minnesota',
     'Standard Oil',
     'Auden',
     'Africa',
     'Gunpowder Plot',
     'yellow',
     'Grant',
     'Kilimanjaro',
     'Hastings',
     'Poseidon',
     'Fidel Castro',
     'Sacco and Vanzetti',
     'Munich Massacre',
/*C-Set Bowl 2015-16 Round 5*/'ISIS',
     'Matthew Perry',
     'Rome',
     'Texas',
     'Sinclair',
     'Sumer',
     'Dubai',
     'Cicero',
     'Verdun',
     'Scopes Trial',
     'Security Council',
     'elephants',
     'Inca',
     'Irish Potato Famine',
     'Containment',
     'germ theory',
     'Marie Antoinette',
     'Sitting Bull',
     'Stradivarius',
     'RFK',
     'Dead Sea',
     'Luddites',
     'Scrabble',
     'Westphalia',
     'Indonesia',
     'Sumner',
     'Martin van Buren',
/*C-Set Bowl 2015-16 Round 6*/'San Jacinto',
     'Saladin',
     'Franco-Prussian War',
     'DC',
     'Caspian Sea',
     'Trenton',
     'Pancho Villa',
     'McCormick',
     'Ghent',
     'Theseus',
     'atheism',
     'Greece',
     'Chavez',
     'Beethoven',
     'Dreadnought',
     'Broadcast of War of the Worlds',
     'Peter the Great',
     'Panama Canal',
     'freedom',
     'Lenin',
     'Burr',
     'Jainism',
     'Robespierre',
     'Degas',
     'First Inaugural Address of FDR',
     'Samurai',
     'Akhenaten',
/*C-Set Bowl 2015-16 Round 7*/'Taj Mahal',
     'Jack the Ripper',
     'More',
     'Colorado River',
     'Berlin',
     'Wallace',
     'Achebe',
     'Zimmerman telegram',
     'marathon',
     'Bismark',
     'McCarthy',
     'Garvey',
     'Labour Party',
     'newspapers',
     'Pinkerton',
     'thirteen',
     'Olympic',
     'Britain',
     'TPP',
     'Oklahoma City Bombing',
     'kidnapping of Charles Lindbergh, Jr',
     'tsunami',
     'Paris Commune',
     'Davis',
     'Hammurabi',
     'affirmative action',
     'San Francisco',
/*C-Set Bowl 2015-16 Round 8*/'Charlemagne',
     'Whig',
     'Erasumus',
     'Nader',
     'Assassination of McKinley',
     'Copland',
     'Boston',
     'Denmark',
     'Donald Duck',
     'Japanese American internment',
     'Zulu',
     'Prime Minister of Israel',
     'Keynes',
     'South China Sea',
     'Salamis',
     '1848',
     'Whiskey Rebellion',
     'Cairo',
     'Hungary',
     'Apollo 13',
     'Opium Wars',
     'Black Lives Matter',
     'Third of May, 1808',
     'Gulf of Mexico',
     'Mason-Dixon line',
     'Marne River',
     'Erie Canal',
/*C-Set Bowl 2015-16 Round 9*/'Nuremberg trials',
     'Poland',
     'Ben Carson',
     'Tarquinius Superbus',
     'Du Bois',
     'Otto I',
     'Shakers',
     'parking spaces',
     'Calhoun',
     'Beowulf',
     'Cyrus the Great',
     'Switzerland',
     'Duke',
     'Brazil',
     'Ravel',
     'Jesse James',
     'Stamp Act',
     'Asoka the Great',
     'Fremont',
     'Nast',
     'St. Bartholomew Day Massacre',
     'Maori',
     'Allen',
     'Tilden',
     'Ho Chi Minh',
     'France',
     'Gulf War',
/*C-Set Bowl 2015-16 Round 10*/'MacArthur',
     'New York City',
     'Spain and Portugal',          
     'Henry VII',
     'complex numbers',
     'Benjamin Franklin',
     'Ansel Adams',
     'Trail of Tears',
     'Margaret Mead',
     'Afghanistan',
     'Taney',
     'Tamerlane',
     'Alfred the Great',
     'Second Boer War',
     'mercenary',
     'Winfield Scott',
     'Jonestown',
     'Nasser',
     'Sanskrit',
     'dwarfs',
     'Poland',
     'Maginot Line',
     'John Jay',
     'Tang Dynasty',
     'Henry Clay',
     'Argentina',
     'Sepoy Mutiny',
/*C-set bee 2018 rd 1*/'Israel',
     'Valley Forge',
     'India',
     'Singing',
     'Norman Rockwell',
     'Cyprus',
     'Crimean War',
     'Gold',
     'Iran Hostage Crisis',
     'Red Army',
     'Congress of Vienna',
     'Jefferson',
     'Handel',
     'Siberia',
     'Mexican American War',
     'Cromwell',
     'Muhammad Ali',
     'Pakistan',
     'Andrew Johnson',
     'Princess Diana',
     'Paris Agreement',
     'Cuban Missile Crisis',
     'Prohibition',
     'Florida Keys',
     'Augustus',
     'London',
     'Plymouth',
     'Nicholas II',
     'Squares',
     'Kim',
     'Byzantine Empire',
/*C-Set Bee 2018 rd 2*/'LA',
     'Oliver Hazard Perry',
     'Three Gorges',
     'Magna Carta',
     'Spain',
     'Illinois',
     'Verdun',
     'Clocks',
     'Federalist',
     'Sniper',
     'Monotheism',
     'Magellan',
     'Violin',
     'Tobacco',
     'Hannibal',
     'Dunkirk',
     'Madison',
     'Zulu',
     'Napoleon',
     'Ivan the Terrible',
     'North America',
     'Interstate',
     'Palestine',
     'Trafalgar',
     'DMZ',
     'McCarthy',
     'Japan',
     'Wilhelm II',
     'Katrina',
     'Dust Bowl',
     'Poland',
/*C-Set 2018 Bee Round 3*/'Iroquois',
     'Suleiman the Magnificent',
     'unemployment',
     'Dubai',
     'Tiananmen Square',
     'Treasury',
     'Holy Temple',
     'Pennsylvania',
     'Archbishop of Canterbury',
     'Ukraine',
     'Cambodia',
     'Mozart',
     'Detroit',
     'Polio',
     'Gorbachev',
     'Yom Kippur War',
     'All Quiet on the Western Front',
     'Prague',
     'Vietnam War',
     'Bismarck',
     'Suez Canal',
     'Nashville',
     'Anthony',
     'Mussolini',
     'Football',
     'Ford',
     'Rome',
     'Preamble',
     'Mexico',
     'Textiles',
     'Antietam',
/*C-Set Bee 2018 Final Round*/'Hawaii',
     'Christian Science',
     'Ticonderoga',
     'Copland',
     'Silver',
     'Thermopylae',
     'Japan',
     'Iraq',
     'Stalin',
     'Mughal',
     'South Dakota',
     'Bosworth Field',
     'Whig',
     'Madrid',
     'Colbert',
     'Garibaldi',
     'Las Vegas',
     'Turtle ships',
     'Chicago',
     'Lepanto',
     'Burr',
     'Origin of Species',
     'wagons',
     'First Crusade',
     'Cyrus the Great',
     'Phillipines',
     'Hemingway',
     'Gutenberg Bible',
     'Maori',
     'Iceland',
     'Mecca',
     'Truman',
     'Peasants Revolt',
     'Kentucky',
     'Myanmar',
     'Liberty Leading the People',
     'Dien Bien Phu',
     'Austrian Succession',
     'Gulags',
     'Kant',
     'Stonewall Jackson',
     'Charles V',
     'Ice age',
     'Japanese Internment',
     'trading cards',
     'Puerto Rico',
     'Apollo 11',
     'Mali',
     'Greece',
     'Peru',
     'Habeas Corpus',
     'Russo-Japanese War',
     'Walls',
     'Bannon',
     'Ramesses',
     'Rio Grande',
     'Quartering',
     'Waltz',
     'Cuba',
     'Song',
     'Hudson',
     'Marbury v Madison',
     'Milton',
     'Qaddafi',
     'Patton',
     'Knights of Labor',
     'Gypsys',
     'Oda',
     'Florida',
     'Buddhas',
     'Personality',
     'IBM',
     'Etruscans',
     'Toronto',
     'Lindbergh',
];
