

var answers = [
     'Dust Bowl',
     'Rome',
     'Hawaii',
     'Mogadishu',
     'Mao Zedong',
     'Eisenhower',
     'Amish',
     'The Republic',
     'Battle of Waterloo',
     'Martin Luther',
     'Korea',
     'Eisenhower',
     'Snake River',
     'Ebola',
     'Osiris',
     'Dvorak',
     'USA',
     'Chinese Communist Party',
     'Hull House',
     'Argentina',
     'Tomb of King Tut',
     'Genocide',
     'Mount Everest',
     'Sikhism',
     'Pericles',
     'Florida',
     'Uruguay',
     'Sputnik',
     'Rush Limbaugh',
     'Francis Scott Key',
     'Spanish Civil War',
     'New York City',
     'Texas',
     'Rupert Murdoch',
     'Justinian',
     'Portugal',
     'Wilson',
     'Tale of Two Cities',
     'Bunker Hill',
     'Tubman',
     'Romulus',
     'Henry',
     'Tierra del Fuego',
     'Guernica',
     'Clooney',
     'Ivan the Terrible',
     'Demand',
     'East Germany',
     'D Day',
     'Halley’s Comet',
     'Triangle Shirtwaist',
     'Detroit',
     'Edward I',
     'Great Wall',
     'Missouri Compromise',
     'Snowden',
     'Paine',
     'Conservative',
     'Second Punic War',
     'China',
     'Assassination of JFK',
     'Venice',
     'Mali Empire',
];
